//Arithmetic Operators
let a=5;
let b=2;
 console.log("a =", a, " & b =", b);
// console.log("a+b=", a+b);
// console.log("a-b=", a-b);
// console.log("a*b=", a*b);
// console.log("a/b=", a/b);
// console.log("a%b=", a%b);
// console.log("a**b=", a**b);

//unary operators
//a = a+1;
//a++;
//a =a-1;
//a--;
//console.log("++a=", ++a);
console.log("a++ =", a++); //5
console.log("a =", a); //6
//console.log("--a =", --a);
//console.log("a =", a);
//console.log("a-- =", a--);
//console.log("a =", a);
